using System;
using System.Collections.Generic;
using NUnit.Framework;
using Zmanim.JewishCalendar;
using Parsha = Zmanim.JewishCalendar.JewishCalendar.Parsha;

namespace ZmanimTests
{
    internal class ParshaMap
    {
        public Parsha Name { get; set; }
        public string Date { get; set; }
    }

    [TestFixture]
    class ParshaListTest
    {
        private static IList<ParshaMap> parshaListDiaspora;

        static ParshaListTest()
        {
            parshaListDiaspora = new List<ParshaMap>
            {
                new() { Name = Parsha.VAYIGASH, Date = "1/4/2020" },
                new() { Name = Parsha.VAYECHI, Date = "1/11/2020" },
                new() { Name = Parsha.SHEMOS, Date = "1/18/2020" },
                new() { Name = Parsha.VAERA, Date = "1/25/2020" },
                new() { Name = Parsha.BO, Date = "2/1/2020" },
                new() { Name = Parsha.BESHALACH, Date = "2/8/2020" },
                new() { Name = Parsha.YISRO, Date = "2/15/2020" },
                new() { Name = Parsha.MISHPATIM, Date = "2/22/2020" },
                new() { Name = Parsha.TERUMAH, Date = "2/29/2020" },
                new() { Name = Parsha.TETZAVEH, Date = "3/7/2020" },
                new() { Name = Parsha.KI_SISA, Date = "3/14/2020" },
                new() { Name = Parsha.VAYAKHEL_PEKUDEI, Date = "3/21/2020" },
                new() { Name = Parsha.VAYIKRA, Date = "3/28/2020" },
                new() { Name = Parsha.TZAV, Date = "4/4/2020" },
                new() { Name = Parsha.SHMINI, Date = "4/18/2020" },
                new() { Name = Parsha.TAZRIA_METZORA, Date = "4/25/2020" },
                new() { Name = Parsha.ACHREI_MOS_KEDOSHIM, Date = "5/2/2020" },
                new() { Name = Parsha.EMOR, Date = "5/9/2020" },
                new() { Name = Parsha.BEHAR_BECHUKOSAI, Date = "5/16/2020" },
                new() { Name = Parsha.BAMIDBAR, Date = "5/23/2020" },
                new() { Name = Parsha.NASSO, Date = "6/6/2020" },
                new() { Name = Parsha.BEHAALOSCHA, Date = "6/13/2020" },
                new() { Name = Parsha.SHLACH, Date = "6/20/2020" },
                new() { Name = Parsha.KORACH, Date = "6/27/2020" },
                new() { Name = Parsha.CHUKAS_BALAK, Date = "7/4/2020" },
                new() { Name = Parsha.PINCHAS, Date = "7/11/2020" },
                new() { Name = Parsha.MATOS_MASEI, Date = "7/18/2020" },
                new() { Name = Parsha.DEVARIM, Date = "7/25/2020" },
                new() { Name = Parsha.VAESCHANAN, Date = "8/1/2020" },
                new() { Name = Parsha.EIKEV, Date = "8/8/2020" },
                new() { Name = Parsha.REEH, Date = "8/15/2020" },
                new() { Name = Parsha.SHOFTIM, Date = "8/22/2020" },
                new() { Name = Parsha.KI_SEITZEI, Date = "8/29/2020" },
                new() { Name = Parsha.KI_SAVO, Date = "9/5/2020" },
                new() { Name = Parsha.NITZAVIM_VAYEILECH, Date = "9/12/2020" },
                new() { Name = Parsha.HAAZINU, Date = "9/26/2020" },
                new() { Name = Parsha.BERESHIS, Date = "10/17/2020" },
                new() { Name = Parsha.NOACH, Date = "10/24/2020" },
                new() { Name = Parsha.LECH_LECHA, Date = "10/31/2020" },
                new() { Name = Parsha.VAYERA, Date = "11/7/2020" },
                new() { Name = Parsha.CHAYEI_SARA, Date = "11/14/2020" },
                new() { Name = Parsha.TOLDOS, Date = "11/21/2020" },
                new() { Name = Parsha.VAYETZEI, Date = "11/28/2020" },
                new() { Name = Parsha.VAYISHLACH, Date = "12/5/2020" },
                new() { Name = Parsha.VAYESHEV, Date = "12/12/2020" },
                new() { Name = Parsha.MIKETZ, Date = "12/19/2020" },
                new() { Name = Parsha.VAYIGASH, Date = "12/26/2020" },
                new() { Name = Parsha.VAYECHI, Date = "1/2/2021" },
                new() { Name = Parsha.SHEMOS, Date = "1/9/2021" },
                new() { Name = Parsha.VAERA, Date = "1/16/2021" },
                new() { Name = Parsha.BO, Date = "1/23/2021" },
                new() { Name = Parsha.BESHALACH, Date = "1/30/2021" },
                new() { Name = Parsha.YISRO, Date = "2/6/2021" },
                new() { Name = Parsha.MISHPATIM, Date = "2/13/2021" },
                new() { Name = Parsha.TERUMAH, Date = "2/20/2021" },
                new() { Name = Parsha.TETZAVEH, Date = "2/27/2021" },
                new() { Name = Parsha.KI_SISA, Date = "3/6/2021" },
                new() { Name = Parsha.VAYAKHEL_PEKUDEI, Date = "3/13/2021" },
                new() { Name = Parsha.VAYIKRA, Date = "3/20/2021" },
                new() { Name = Parsha.TZAV, Date = "3/27/2021" },
                new() { Name = Parsha.SHMINI, Date = "4/10/2021" },
                new() { Name = Parsha.TAZRIA_METZORA, Date = "4/17/2021" },
                new() { Name = Parsha.ACHREI_MOS_KEDOSHIM, Date = "4/24/2021" },
                new() { Name = Parsha.EMOR, Date = "5/1/2021" },
                new() { Name = Parsha.BEHAR_BECHUKOSAI, Date = "5/8/2021" },
                new() { Name = Parsha.BAMIDBAR, Date = "5/15/2021" },
                new() { Name = Parsha.NASSO, Date = "5/22/2021" },
                new() { Name = Parsha.BEHAALOSCHA, Date = "5/29/2021" },
                new() { Name = Parsha.SHLACH, Date = "6/5/2021" },
                new() { Name = Parsha.KORACH, Date = "6/12/2021" },
                new() { Name = Parsha.CHUKAS, Date = "6/19/2021" },
                new() { Name = Parsha.BALAK, Date = "6/26/2021" },
                new() { Name = Parsha.PINCHAS, Date = "7/3/2021" },
                new() { Name = Parsha.MATOS_MASEI, Date = "7/10/2021" },
                new() { Name = Parsha.DEVARIM, Date = "7/17/2021" },
                new() { Name = Parsha.VAESCHANAN, Date = "7/24/2021" },
                new() { Name = Parsha.EIKEV, Date = "7/31/2021" },
                new() { Name = Parsha.REEH, Date = "8/7/2021" },
                new() { Name = Parsha.SHOFTIM, Date = "8/14/2021" },
                new() { Name = Parsha.KI_SEITZEI, Date = "8/21/2021" },
                new() { Name = Parsha.KI_SAVO, Date = "8/28/2021" },
                new() { Name = Parsha.NITZAVIM, Date = "9/4/2021" },
                new() { Name = Parsha.VAYEILECH, Date = "9/11/2021" },
                new() { Name = Parsha.HAAZINU, Date = "9/18/2021" },
                new() { Name = Parsha.BERESHIS, Date = "10/2/2021" },
                new() { Name = Parsha.NOACH, Date = "10/9/2021" },
                new() { Name = Parsha.LECH_LECHA, Date = "10/16/2021" },
                new() { Name = Parsha.VAYERA, Date = "10/23/2021" },
                new() { Name = Parsha.CHAYEI_SARA, Date = "10/30/2021" },
                new() { Name = Parsha.TOLDOS, Date = "11/6/2021" },
                new() { Name = Parsha.VAYETZEI, Date = "11/13/2021" },
                new() { Name = Parsha.VAYISHLACH, Date = "11/20/2021" },
                new() { Name = Parsha.VAYESHEV, Date = "11/27/2021" },
                new() { Name = Parsha.MIKETZ, Date = "12/4/2021" },
                new() { Name = Parsha.VAYIGASH, Date = "12/11/2021" },
                new() { Name = Parsha.VAYECHI, Date = "12/18/2021" },
                new() { Name = Parsha.SHEMOS, Date = "12/25/2021" },
                new() { Name = Parsha.VAERA, Date = "1/1/2022" },
                new() { Name = Parsha.BO, Date = "1/8/2022" },
                new() { Name = Parsha.BESHALACH, Date = "1/15/2022" },
                new() { Name = Parsha.YISRO, Date = "1/22/2022" },
                new() { Name = Parsha.MISHPATIM, Date = "1/29/2022" },
                new() { Name = Parsha.TERUMAH, Date = "2/5/2022" },
                new() { Name = Parsha.TETZAVEH, Date = "2/12/2022" },
                new() { Name = Parsha.KI_SISA, Date = "2/19/2022" },
                new() { Name = Parsha.VAYAKHEL, Date = "2/26/2022" },
                new() { Name = Parsha.PEKUDEI, Date = "3/5/2022" },
                new() { Name = Parsha.VAYIKRA, Date = "3/12/2022" },
                new() { Name = Parsha.TZAV, Date = "3/19/2022" },
                new() { Name = Parsha.SHMINI, Date = "3/26/2022" },
                new() { Name = Parsha.TAZRIA, Date = "4/2/2022" },
                new() { Name = Parsha.METZORA, Date = "4/9/2022" },
                new() { Name = Parsha.ACHREI_MOS, Date = "4/30/2022" },
                new() { Name = Parsha.KEDOSHIM, Date = "5/7/2022" },
                new() { Name = Parsha.EMOR, Date = "5/14/2022" },
                new() { Name = Parsha.BEHAR, Date = "5/21/2022" },
                new() { Name = Parsha.BECHUKOSAI, Date = "5/28/2022" },
                new() { Name = Parsha.BAMIDBAR, Date = "6/4/2022" },
                new() { Name = Parsha.NASSO, Date = "6/11/2022" },
                new() { Name = Parsha.BEHAALOSCHA, Date = "6/18/2022" },
                new() { Name = Parsha.SHLACH, Date = "6/25/2022" },
                new() { Name = Parsha.KORACH, Date = "7/2/2022" },
                new() { Name = Parsha.CHUKAS, Date = "7/9/2022" },
                new() { Name = Parsha.BALAK, Date = "7/16/2022" },
                new() { Name = Parsha.PINCHAS, Date = "7/23/2022" },
                new() { Name = Parsha.MATOS_MASEI, Date = "7/30/2022" },
                new() { Name = Parsha.DEVARIM, Date = "8/6/2022" },
                new() { Name = Parsha.VAESCHANAN, Date = "8/13/2022" },
                new() { Name = Parsha.EIKEV, Date = "8/20/2022" },
                new() { Name = Parsha.REEH, Date = "8/27/2022" },
                new() { Name = Parsha.SHOFTIM, Date = "9/3/2022" },
                new() { Name = Parsha.KI_SEITZEI, Date = "9/10/2022" },
                new() { Name = Parsha.KI_SAVO, Date = "9/17/2022" },
                new() { Name = Parsha.NITZAVIM, Date = "9/24/2022" },
                new() { Name = Parsha.VAYEILECH, Date = "10/1/2022" },
                new() { Name = Parsha.HAAZINU, Date = "10/8/2022" },
                new() { Name = Parsha.BERESHIS, Date = "10/22/2022" },
                new() { Name = Parsha.NOACH, Date = "10/29/2022" },
                new() { Name = Parsha.LECH_LECHA, Date = "11/5/2022" },
                new() { Name = Parsha.VAYERA, Date = "11/12/2022" },
                new() { Name = Parsha.CHAYEI_SARA, Date = "11/19/2022" },
                new() { Name = Parsha.TOLDOS, Date = "11/26/2022" },
                new() { Name = Parsha.VAYETZEI, Date = "12/3/2022" },
                new() { Name = Parsha.VAYISHLACH, Date = "12/10/2022" },
                new() { Name = Parsha.VAYESHEV, Date = "12/17/2022" },
                new() { Name = Parsha.MIKETZ, Date = "12/24/2022" },
                new() { Name = Parsha.VAYIGASH, Date = "12/31/2022" },
                new() { Name = Parsha.VAYECHI, Date = "1/7/2023" },
                new() { Name = Parsha.SHEMOS, Date = "1/14/2023" },
                new() { Name = Parsha.VAERA, Date = "1/21/2023" },
                new() { Name = Parsha.BO, Date = "1/28/2023" },
                new() { Name = Parsha.BESHALACH, Date = "2/4/2023" },
                new() { Name = Parsha.YISRO, Date = "2/11/2023" },
                new() { Name = Parsha.MISHPATIM, Date = "2/18/2023" },
                new() { Name = Parsha.TERUMAH, Date = "2/25/2023" },
                new() { Name = Parsha.TETZAVEH, Date = "3/4/2023" },
                new() { Name = Parsha.KI_SISA, Date = "3/11/2023" },
                new() { Name = Parsha.VAYAKHEL_PEKUDEI, Date = "3/18/2023" },
                new() { Name = Parsha.VAYIKRA, Date = "3/25/2023" },
                new() { Name = Parsha.TZAV, Date = "4/1/2023" },
                new() { Name = Parsha.SHMINI, Date = "4/15/2023" },
                new() { Name = Parsha.TAZRIA_METZORA, Date = "4/22/2023" },
                new() { Name = Parsha.ACHREI_MOS_KEDOSHIM, Date = "4/29/2023" },
                new() { Name = Parsha.EMOR, Date = "5/6/2023" },
                new() { Name = Parsha.BEHAR_BECHUKOSAI, Date = "5/13/2023" },
                new() { Name = Parsha.BAMIDBAR, Date = "5/20/2023" },
                new() { Name = Parsha.NASSO, Date = "6/3/2023" },
                new() { Name = Parsha.BEHAALOSCHA, Date = "6/10/2023" },
                new() { Name = Parsha.SHLACH, Date = "6/17/2023" },
                new() { Name = Parsha.KORACH, Date = "6/24/2023" },
                new() { Name = Parsha.CHUKAS_BALAK, Date = "7/1/2023" },
                new() { Name = Parsha.PINCHAS, Date = "7/8/2023" },
                new() { Name = Parsha.MATOS_MASEI, Date = "7/15/2023" },
                new() { Name = Parsha.DEVARIM, Date = "7/22/2023" },
                new() { Name = Parsha.VAESCHANAN, Date = "7/29/2023" },
                new() { Name = Parsha.EIKEV, Date = "8/5/2023" },
                new() { Name = Parsha.REEH, Date = "8/12/2023" },
                new() { Name = Parsha.SHOFTIM, Date = "8/19/2023" },
                new() { Name = Parsha.KI_SEITZEI, Date = "8/26/2023" },
                new() { Name = Parsha.KI_SAVO, Date = "9/2/2023" },
                new() { Name = Parsha.NITZAVIM_VAYEILECH, Date = "9/9/2023" },
                new() { Name = Parsha.HAAZINU, Date = "9/23/2023" },
                new() { Name = Parsha.BERESHIS, Date = "10/14/2028" },
                new() { Name = Parsha.NOACH, Date = "10/21/2028" },
                new() { Name = Parsha.LECH_LECHA, Date = "10/28/2028" },
                new() { Name = Parsha.VAYERA, Date = "11/4/2028" },
                new() { Name = Parsha.CHAYEI_SARA, Date = "11/11/2028" },
                new() { Name = Parsha.TOLDOS, Date = "11/18/2028" },
                new() { Name = Parsha.VAYETZEI, Date = "11/25/2028" },
                new() { Name = Parsha.VAYISHLACH, Date = "12/2/2028" },
                new() { Name = Parsha.VAYESHEV, Date = "12/9/2028" },
                new() { Name = Parsha.MIKETZ, Date = "12/16/2028" },
                new() { Name = Parsha.VAYIGASH, Date = "12/23/2028" },
                new() { Name = Parsha.VAYECHI, Date = "12/30/2028" },
                new() { Name = Parsha.SHEMOS, Date = "1/6/2029" },
                new() { Name = Parsha.VAERA, Date = "1/13/2029" },
                new() { Name = Parsha.BO, Date = "1/20/2029" },
                new() { Name = Parsha.BESHALACH, Date = "1/27/2029" },
                new() { Name = Parsha.YISRO, Date = "2/3/2029" },
                new() { Name = Parsha.MISHPATIM, Date = "2/10/2029" },
                new() { Name = Parsha.TERUMAH, Date = "2/17/2029" },
                new() { Name = Parsha.TETZAVEH, Date = "2/24/2029" },
                new() { Name = Parsha.KI_SISA, Date = "3/3/2029" },
                new() { Name = Parsha.VAYAKHEL_PEKUDEI, Date = "3/10/2029" },
                new() { Name = Parsha.VAYIKRA, Date = "3/17/2029" },
                new() { Name = Parsha.TZAV, Date = "3/24/2029" },
                new() { Name = Parsha.SHMINI, Date = "4/14/2029" },
                new() { Name = Parsha.TAZRIA_METZORA, Date = "4/21/2029" },
                new() { Name = Parsha.ACHREI_MOS_KEDOSHIM, Date = "4/28/2029" },
                new() { Name = Parsha.EMOR, Date = "5/5/2029" },
                new() { Name = Parsha.BEHAR_BECHUKOSAI, Date = "5/12/2029" },
                new() { Name = Parsha.BAMIDBAR, Date = "5/19/2029" },
                new() { Name = Parsha.NASSO, Date = "5/26/2029" },
                new() { Name = Parsha.BEHAALOSCHA, Date = "6/2/2029" },
                new() { Name = Parsha.SHLACH, Date = "6/9/2029" },
                new() { Name = Parsha.KORACH, Date = "6/16/2029" },
                new() { Name = Parsha.CHUKAS, Date = "6/23/2029" },
                new() { Name = Parsha.BALAK, Date = "6/30/2029" },
                new() { Name = Parsha.PINCHAS, Date = "7/7/2029" },
                new() { Name = Parsha.MATOS_MASEI, Date = "7/14/2029" },
                new() { Name = Parsha.DEVARIM, Date = "7/21/2029" },
                new() { Name = Parsha.VAESCHANAN, Date = "7/28/2029" },
                new() { Name = Parsha.EIKEV, Date = "8/4/2029" },
                new() { Name = Parsha.REEH, Date = "8/11/2029" },
                new() { Name = Parsha.SHOFTIM, Date = "8/18/2029" },
                new() { Name = Parsha.KI_SEITZEI, Date = "8/25/2029" },
                new() { Name = Parsha.KI_SAVO, Date = "9/1/2029" },
                new() { Name = Parsha.NITZAVIM, Date = "9/8/2029" },
                new() { Name = Parsha.VAYEILECH, Date = "9/15/2029" },
                new() { Name = Parsha.HAAZINU, Date = "9/22/2029" },
            };
        }

        [TestCaseSource(nameof(parshaListDiaspora))]
        public void OutsideIsraelList(ParshaMap parshaMap)
        {
            var jewishCalendar = new JewishCalendar();

            Assert.That(jewishCalendar.GetParshah(DateTime.Parse(parshaMap.Date)), Is.EqualTo(parshaMap.Name));
        }
    }
}